name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Primer paso
    # Este paso toma todo el código que está en el repositorio
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Obteniendo versionamiento automático
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    # Segundo paso
    # Este paso se autentica en docker hub
    - name: Authenticated docker hub
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login en docker hub"
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
        echo "Finalizando login en docker hub"

    # Tercer paso
    # Construir la imagen con docker
    - name: Build Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build --tag mate0laya/docker-graphql:$NEW_VERSION .
        docker build --tag mate0laya/docker-graphql:latest .

    # Cuarto paso
    # Subiendo imagen a docker hub
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push mate0laya/docker-graphql:$NEW_VERSION
        docker push mate0laya/docker-graphql:latest
